### ISSUE TITLE
open pdf in customized external pdf reader

### ISSUE THREAD

**Issue by sylph520** [retorquere/zotero-open-pdf#10]
Hello, thank you for your work. 
I'm wondering would it be possible to make a customized setting that we can choose what external pdf viewer to use (other than the system default pdf viewer)? It'd be better that multiple right click menus (or other possible approaches) to let us choose to open the pdf in viewer A (e.g., menu "open with adobe pdf viewer") or viewer B (e.g., menu "open with sumatra pdf viewer")?

**Comment by retorquere** [comment]
It's technically possible but too big for me to take on, sorry.
