### ISSUE TITLE
Applying the custom viewer on windows, "arg.toLowercase is not a function" error message

### ISSUE THREAD

**Issue by psj8710** [retorquere/zotero-open-pdf#13]
I tried to use this plug-in to launch MS Edge browser as a custom (not system default) pdf reader on a windows computer, but I kept encountered the same error message like this: "arg.toLowercase is not a function".
I was using the example values on the readme page with the correct full path of the windows system, but later I found out that the example value was for macOS. 

After trying a few different ways, I found out how to do solve the issue, so this post is for the people who might encounter the same situation. 

The solution is simple. You just need to give a full path including the execution file name with **the quotation marks.** 
Below is an example for using MS Edge as a custom external pdf viewer, which worked for me without an issue.  

`"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" -a @pdf`

**Comment by retorquere** [comment]
I've added it in the readme as a sample
