### ISSUE TITLE
How to add a new String entry in Zotero Config Editor to add extra entries for your own PDF viewers/editor of choice?

### ISSUE THREAD

**Issue by nhan000** [retorquere/zotero-open-pdf#14]
Right clicking only brings up "Copy" and "Select all". The "File" and "Edit" buttons also don't bring up anything that help create a new value. 

![image](https://github.com/retorquere/zotero-open-pdf/assets/85216095/648f17d3-77f7-433f-be14-4cd8ff6cd91a)

I'm using the latest Zotero 7 beta version (7.0.0-beta.74+2e8073ab9 (64-bit)) on Windows 11 and the latest version of this plugin (Version 0.0.11).

Thank you!

**Comment by retorquere** [comment]
Turns out you just start typing and the create button appears.

**Comment by nhan000** [comment]
Thank you! It works for me now. 

Hope this screenshot would be helpful to someone.
![image](https://github.com/retorquere/zotero-open-pdf/assets/85216095/da3e0bda-b56b-4491-bf48-06e09046514b)
