### ISSUE TITLE
Add option "Open with..."

### ISSUE THREAD

**Issue by feng-li** [retorquere/zotero-open-pdf#6]
I like the addon I am wondering if it is possible to add a right-click option "Open PDF with..." 

I share my PDFs with my students and colleagues via Email client. I guess many scholars do so. At the moment, I have to click "Show File" and allocate the PDF in a system file browser, and then do another right-click and "open with Thunderbird" to attach it.

If I have the "open PDF with..." option, I could easily attach the PDF file to an email client like Thunderbird. This option is also useful if one has different PDF readers for different purposes.

**Comment by retorquere** [comment]
You would have to browse to the thunderbird executable every time. That doesn't seem much more convenient. The "open with Thunderbird" is something Thunderbird adds to the file explorer, those aren't available to Zotero.

Wouldn't it be easier to put a shortcut to thunderbird on the desktop and drag attachments from zotero onto that? I think that should work.

**Comment by feng-li** [comment]
Th

> You would have to browse to the thunderbird executable every time. That doesn't seem much more convenient. The "open with Thunderbird" is something Thunderbird adds to the file explorer, those aren't available to Zotero.
> 
> Wouldn't it be easier to put a shortcut to thunderbird on the desktop and drag attachments from zotero onto that? I think that should work.

I now think it is more complicated than I initially thought. I thought just invoke the system menu like this

![Screenshot from 2022-11-13 15-45-49](https://user-images.githubusercontent.com/1174311/201511561-177bba9c-a7ea-4dae-b3c2-94cc741f9e06.png)

**Comment by retorquere** [comment]
I'm not sure that is possible from zotero.

**Comment by retorquere** [comment]
I don't know how to do this, sorry.
