### ISSUE TITLE
Add keyboard shortcut for "Open in External Viewer"

### ISSUE THREAD

**Issue by champagnealexandre** [retorquere/zotero-open-pdf#7]
First, thank you @retorquere for another very useful add-on.

Is there a way to add a keyboard shortcut to the function in title? I’ve tried through the usual "Keyboard shortcuts" in macOS and it doesn’t work since it’s a context menu and not a menu from the menu bar.

If it is not, would you consider adding such an option? Something like CMD-Enter or CTRL-Enter would be very useful.

Thank you!

**Comment by retorquere** [comment]
I think [Zutilo](https://github.com/wshanks/Zutilo) can add shortcuts. I'm not really familiar with how shortcuts work in Zotero.

**Comment by champagnealexandre** [comment]
I’ve just checked and Zutilo only supports native Zotero functions + a handful from BBT, and the few last requests to add more shortcuts haven’t been answered unfortunately.

**Comment by champagnealexandre** [comment]
Other suggestion: if zotero-open-pdf could add an entry to the following menu like other plugins do, it would be trivial to add the keyboard shortcut through standard means (i.e., macOS’ keyboard shortcuts pref pane):

<img width="440" alt="image" src="https://user-images.githubusercontent.com/30211986/207652989-4a84fb36-b9a0-4259-8aac-b7d2c47b09d9.png">

Do you think that’s possible?

**Comment by retorquere** [comment]
The tools menu isn't really a good place for this. You'd have to have an item selected before you could use the menu item; that's a better fit for the (existing) right-click menu.

It'd be trivial to add an action Zutilo could call though.

**Comment by champagnealexandre** [comment]
Right. Unfortunately Zutilo isn’t able to call zotero-open-pdf’s shortcuts, and it isn’t updated anymore either.

I have been able to call the shortcut using BetterTouchTools by simulating keystrokes, it’s not ideal as there’s some lag obviously, but I guess that’s the best I can do.

Thanks!
