### ISSUE TITLE
[bug report] closing + reopening the window makes the menu item disappear

### ISSUE THREAD

**Issue by champagnealexandre** [retorquere/zotero-open-pdf#8]
Zotero version: 6.0.20
Plugin version: 0.0.4

Tested with the "open PDFs using" option set to "system default" and "zotero", bug is present with both.

**Steps to reproduce:**
1. install + enable plugin
2. close the window
3. reopen the window

**Before step 2:**
<img width="485" alt="image" src="https://user-images.githubusercontent.com/30211986/213733509-5034cf36-0fe4-412e-956d-c252fe7844c9.png">

**After step 2:**
<img width="455" alt="image" src="https://user-images.githubusercontent.com/30211986/213733685-62736a31-824a-4817-b577-40ee8a79fdb8.png">

**Comment by champagnealexandre** [comment]
@retorquere have you been able to reproduce this bug?

**Comment by retorquere** [comment]
It was a long standing bug due to how my plugin loaded. build 0.0.5.13 should behave better, can you try that?

**Comment by champagnealexandre** [comment]
Seems to be working fine now, thank you so much!
