### ISSUE TITLE
Small updates

### ISSUE THREAD

**Issue by mjthoraval** [retorquere/zotero-open-pdf#9]
Thank you very much for making this plugin compatible with Zotero 7.
I just have a few minor remarks:
1) The version needs to be updated in manifest.json. It still gives Version 0.0.1 in the Add-ons Manager of Zotero 7 beta.
2) Most Zotero plugins are not Zotero 7 compatible yet. It is probably worth adding a remark in the README that this one is Zotero 7 ready?
3) It was [suggested in the Zotero forums](https://forums.zotero.org/discussion/comment/435505) to update the [list of plugins](https://www.zotero.org/support/plugins) to list the ones compatible with Zotero 7. Do you plan to add this plugin there? Could you mark in that page which of your plugins are Zotero 7 compatible?

**Comment by retorquere** [comment]
Done.
